package br.com.asgard.domain.enums;

import lombok.Getter;

@Getter
public enum StatusNegativacaoBoleto {
    NEGATIVACAO_BOLETO_AGENDADA,
    NEGATIVACAO_BOLETO_AGENDAMENTO_EXCLUIDO,
    NEGATIVACAO_BOLETO_INCLUSAO_ENVIADA_COMANDO,
    NEGATIVACAO_BOLETO_EXCLUSAO_ENVIADA_COMANDO,
    NEGATIVACAO_BOLETO_INCLUSAO_PROCESSADA_SUCESSO,
    NEGATIVACAO_BOLETO_EXCLUSAO_PROCESSADA_SUCESSO,
    NEGATIVACAO_BOLETO_INCLUSAO_PROCESSADA_FALHA,
    NEGATIVACAO_BOLETO_EXCLUSAO_PROCESSADA_FALHA,
    NEGATIVACAO_BOLETO_INCLUSAO_CONFIRMADA_BUREAU,
    NEGATIVACAO_BOLETO_EXCLUSAO_CONFIRMADA_BUREAU,
    NEGATIVACAO_BOLETO_INCLUSAO_RECUSADA_BUREAU,
    NEGATIVACAO_BOLETO_EXCLUSAO_RECUSADA_BUREAU,
    NEGATIVACAO_BOLETO_INCLUSAO_EFETIVADA_BUREAU,
    NEGATIVACAO_BOLETO_EXCLUSAO_EFETIVADA_BUREAU,
}
